language: node_js
node_js:
  - "node"
cache: yarn

script:
  - yarn build

after_success:
  - yarn global add firebase-tools
  - firebase deploy --token=${FIREBASE_TOKEN} -P default
  - firebase deploy --token=${FIREBASE_TOKEN} -P dev
